### ISSUE TITLE
Allow token from secretKeyRef for the Hook resource

### ISSUE THREAD

**Issue by tvandinther** [crossplane-contrib/provider-gitlab#153]
### What problem are you facing?
I would like to create a Gitlab hook with a token specified in a kubernetes secret. Currently I would have to create a composition with the secret to use patching. This method also displays the token directly on the hook resource.

### How could Crossplane help solve your problem?
Introduce a `spec.forProvider.tokenRef` field for this functionality.

**Comment by dariozachow** [comment]
thats a duplicate for this Issue https://github.com/crossplane-contrib/provider-gitlab/issues/133

**Comment by tvandinther** [comment]
Yes it is, thanks for your contribution.
