### ISSUE TITLE
Support  gitlab project access tokens resource.

### ISSUE THREAD

**Issue by iyurev** [crossplane-contrib/provider-gitlab#58]
### What problem are you facing?

In our environment we use some automation flow to create a gitops projects in a local gitlab instance,  it’d be great to have an opportunity also create  [gitlab project access token](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html)  for each gitops project to use it then in our main CI/CD pipeline.

### How could Crossplane help solve your problem?
To solve this it requires  to implement one more controller in GitLab Provider  to manage access token resource in Crossplane way. 
If it sounds reasonable  I'd  like to implement this functionality.

**Comment by MisterMX** [comment]
@iyurev sounds reasonable. If you want to implement this, go ahead. Thanks in advance!
